Добавил отображение карты города при запуске приложения
NelsonBeard/Carshering pull request #1
Opened 2022-05-01 15:24 UTC by NelsonBeard

2022-05-01 22:21 UTC, ipopov-belkacar commented on app/src/main/java/com/carshering/data/CommonCity.kt
> +    var city = UFA
1) Зачем заведена изменяемая (var) переменная city, если её значение нигде не изменяется? Вообще, по умолчанию лучше все переменные делать val (неизменяемыми), если не предполагается, что значение переменной будет изменяться. Это и логичнее, и компилятору работу облегчает. var должен быть всегда осознанным решением, потому что как только ты делаешь переменную var - ты говоришь всем разработчикам, которые будет иметь с твоим кодом дело: "эту переменную можно менять из любого места в приложении, откуда я могу до неё дотянуться, и у меня ничего не сломается".


2) Метод всегда имеет название. Метод всегда должен делать ровно то, что обозначено в его названии, ни больше, ни меньше. Метод должен совершать только одно действие - то, то написано в его названии. Сюрпризов быть не должно.


3) Метод setSomeEntity() никогда не должен возвращать значение. Это - грубое нарушение контракта языка и пункта 2). Метод setSomeEntity() всегда должен только изменять значение переменной someEntity. А метод getSomeEntity() -  должен только возвращать значение someEntity. В твоём случае, метод setCity() не имеет никакого отношения к изменению переменной city.

Про сеттеры и геттеры можно почитать тут https://www.javatpoint.com/encapsulation. На javatpoint можно почитать и другие базовые понятия по неймингу и стилю кода.

2022-05-01 22:21 UTC, ipopov-belkacar commented on app/src/main/java/com/carshering/ui/MainActivityMap.kt
> +        val (latLng, zoom) = CommonCity().setCity()
Наглядная демонстрация неочевидности нейминга методов и переменных. Почему метод setCity() возвращает пару latlng, zoom? Судя по его названию, он просто изменяет значение города.

2022-05-01 22:21 UTC, ipopov-belkacar commented on app/src/main/java/com/carshering/domain/entity/City.kt
> +    var latLng: LatLng,
Зачем эти переменные var? Ты их где-то изменяешь?

2022-05-02 05:34 UTC, ityulkanov-belkacar requested changes

2022-05-02 05:34 UTC, ityulkanov-belkacar commented on app/src/main/java/com/carshering/ui/MainActivityMap.kt
> +    private lateinit var mMap: GoogleMap
Давай уйдем от названия переменных в стиле **m**Value / **s**Value и будем называть просто value.
Вот тут в целом про [naming convention](https://kotlinlang.org/docs/coding-conventions.html) есть.
m и s раньше использовались для того чтобы визуально разделить статические переменные от членов класса, так как ни динамической подсветки ни таких же мощных IDE как сейчас раньше не было. Сейчас все проще и нужды в этом больше нет, теперь эти префиксы только мешаются.

2022-05-03 05:53 UTC, NelsonBeard commented on build.gradle
> +    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin' version '2.0.1' apply false
Эти плагины прописываются автоматически при создании нового проекта. Зачем они нужны - сейчас почитаю, но знаю, что без них build.gradle файл не синхронизируется. При изменении false на true также синхронизации не происходит

2022-05-04 07:34 UTC, ityulkanov-belkacar commented on app/src/main/java/com/carshering/data/StartPositionManual.kt
> +private val LAT_LNG = LatLng(54.74390, 56.04680)
Я еще добавлю, в этой константе не хватает какой-нибудь отсылки к местоположению, типа LAT_LNG_UFA или что-то такое.

2022-05-04 11:19 UTC, merged