Сверстал bottom sheet для отображения данных об авто и заполнил его.
NelsonBeard/Carshering pull request #3
Opened 2022-05-16 17:08 UTC by NelsonBeard

Вью отображения данных пока сырой, буду дорабатывать

2022-05-23 15:26 UTC, ipopov-belkacar commented on app/src/main/java/com/carshering/ui/Contract.kt
> +        fun initBottomSheet(bottomSheet: RelativeLayout)
Это работает и в другую сторону: в контракте презентер -> вьюха (interface Presenter) должны быть только те методы, которые нужны вьюхе для того, чтобы сообщать о событиях презентеру. Вьюха говорит "onMyButtonCLicked()", и ей фиолетово, что презентер с этим будет делать дальше.

2022-05-23 16:07 UTC, ipopov-belkacar commented on app/src/main/java/com/carshering/ui/Presenter.kt
> +        view?.setCarColorField(colorRussianTitle, colorCode as Int)
Дефолтное значение colorCode у тебя " ", при касте этого значения в Int падаем с ClassCastException.

2022-05-24 07:44 UTC, ityulkanov-belkacar requested changes

2022-05-24 07:44 UTC, ityulkanov-belkacar commented on app/src/main/java/com/carshering/ui/Presenter.kt
> +                    if (markerLatLng == carLatLng) {
Вот тут пря не очень хорошо, по двум причинам:

1. Ты передаешь маркер в презентер, я бы не стал этого делать по нескольким причинам:

- С одной стороны, да, мы можем сказать что маркер не является объектом UI, так как это просто класс с набором полей (что-то вроде дата класса), но косвенно он все же нужен для отрисовки UI и отображаения данных.
- Кроме этого, это лишняя зависимость от стороннего фреймворка в презентере, если ту будешь переходить на другой сервис картографии, то зацепит и презентер.
- Ну и в конце концов лучше всего между слоями передавать не объекты, а какие-то уникальные примитивы  (айдишки) по которым конечный получатель достанет сам нужный ему объект. По сути тут так и есть, но вместо одного LatLng ты передаешь весь маркер.

2. Использование LatLng в качестве уникального параметра. Во первых это с очень маленькой долей вероятности может быть не уникально, во вторых это не постоянный параметр. В то же время у тебя есть айдишка. Я бы использовал именно айдишку авто, по клику вытаскивал ее из маркера (придумай как это сделать, есть как минимум два способа) и передавал ее в презентер.

2022-05-24 07:44 UTC, ityulkanov-belkacar commented on app/src/main/res/layout/car_info_bottom_sheet.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
А давай сделаем то же самое на ConstraintLayout

2022-05-24 09:39 UTC, NelsonBeard commented on app/src/main/res/layout/car_info_bottom_sheet.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Переделал. 
Делал с RelativeLayout, потому что до этого не верстал на это лэйауте,  хотел попроактиковаться. И фигма показывает RelativeLayout. На сколько я понял, на это ориентироваться не стоит, но идею подчерпнул от туда

2022-05-24 10:41 UTC, ityulkanov-belkacar commented on app/src/main/java/com/carshering/ui/Presenter.kt
> +        carDAOImpl.getAllCars(
Получается мы при каждом клике достаем список авто заново? Давай попробуем этого избежать.

2022-07-04 07:42 UTC, merged